apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoproject-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoproject
  template:
    metadata:
      labels:
        name: todoproject
    spec:
      containers:
        - name: todoproject
          image: daviduyaguarij/todoproject
          ports:
          - containerPort: 5173
            name: http