apiVersion: v1
kind: Service
metadata:
  name: todoproject-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      name: http
  selector:
    app: todoproject