apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react
          image: d4viduj/react-app:${{ github.sha }}
          ports:
            - containerPort: 5173
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5173
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5173
            initialDelaySeconds: 20
            periodSeconds: 3
