name: Build, Push, and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: daviduyaguarij/todoproject:${{ github.sha }}

  deploy:
    needs: build-and-push
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to cluster
      uses: mjamaah/kubectl@master
      with:
        config_data: ${{ secrets.kube_config}}
        args: set image --record deployments/deployment.yaml daviduyaguarij=todoproject:${{ github.sha }}
    - name: Verify deployment
      uses: mjamaah/kubectl@master
      with:
        config_data: ${{ secrets.kube_config }}
        args: '"rollout status deployments/deployment.yaml"'